#!/usr/bin/env bash
# Installs nginx web server

sudo apt-get -y update
sudo apt-get -y install nginx

sudo service nginx start
sudo ufw allow 'Nginx HTTP'

sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 777 /var/www -R

echo 'Hello World!' > /var/www/html/index.nginx-debian.html

sudo service nginx restart
