#!/usr/bin/env bash
# Configure a new Nginx server so that /redirect_me is redirecting to another page with a 301 Moved Permanently

sudo apt-get -y update
sudo apt-get -y install nginx

sudo service nginx start
sudo ufw allow 'Nginx HTTP'

sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 777 /var/www -R

echo 'Hello World!' > /var/www/html/index.nginx-debian.html

printf %s "server {
    listen 80;
    listen [::]:80 default_server;

    root   /etc/nginx/html;
    index  index.html index.htm;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}" > /etc/nginx/sites-available/default

sudo service nginx restart
