#!/usr/bin/env bash
# Install customer header
sudo apt update
sudo apt install nginx -y
server_hostname=$(hostname)
echo "add_header X-Served-By $server_hostname;" | sudo tee -a /etc/nginx/sites-available/default > /dev/null
service nginx restart
